name: "deployment"
permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  models: read
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  security-events: write
  statuses: write
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Build:
    uses: ./.github/workflows/maven_build.yml
    with:
      path: dev ## Path to terraform root module (Required)
      enable_TFSEC: true ## (Optional)  Enable TFSEC IaC scans (Private repo requires GitHub enterprise)

  # Deploy:
  #   needs: Build
  #   uses: ./.github/workflows/localstack.yml
  #   with:
  #     path: dev ## Path to terraform root module (Required)
  #     gh_environment: dev ## GH Environment. Default=null - (Optional)
