######################################################
### USER RESPONSIBLE TO CHANGE PATH/DIRECTORY NAME ###
### CURRENTLY dev, stage, prod folders             ###
###                                                ###
### Looks for keyword path: and change the name to ###
### one of above ie dev                            ###
######################################################
name: "Push to Feature Branch"
#permissions: read-all
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!develop'
      - '!stage'
      - '!main'
    
  pull_request:
    branches:
      - main

  # pull_request_review:
  #   types: [submitted]

jobs:
  Maven-build:
    uses: ./.github/workflows/maven_build.yml
    with:
      path: dev # Path to terraform root module (Required)
      enable_TFSEC: true ## (Optional)  Enable TFSEC IaC scans (Private repo requires GitHub enterprise)
